In [17]:
class Employee:
    # Class variable to count the number of employees
    employee_count = 0
    total_salary = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1
        Employee.total_salary += salary

    @classmethod
    def average_salary(cls):
        if cls.employee_count == 0:
            return 0
        return cls.total_salary / cls.employee_count


# FulltimeEmployee class inheriting from Employee
class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)


if __name__ == "__main__":
    # Creating instances of Employee and FulltimeEmployee
    emp1 = Employee("Alice", "Smith", 70000, "Engineering")
    emp2 = Employee("Bob", "Johnson", 80000, "Marketing")
    full_emp1 = FulltimeEmployee("Charlie", "Brown", 90000, "Sales")
    full_emp2 = FulltimeEmployee("David", "Williams", 100000, "HR")

    # Displaying the average salary
    print("Average salary of employees:", Employee.average_salary())

    # Displaying the number of employees
    print("Total number of employees:", Employee.employee_count)


Average salary of employees: 85000.0
Total number of employees: 4


In [16]:
import numpy as np

#function to replace the maximum value in an array of axis x and y based on the condition
def replace_maxmium(array, replace_value, axis):
    result = np.where(array == np.max(
        array, axis=1).reshape(-1, 1), 0 * array, array)
    print(result)


 #creating a random vector of size 29 which is having in the range of 1-20
randarr = np.random.random_sample(20) * 20 + 1
print(randarr)

    #reshaping the array to 4 by 5 in random20
randarr_4by5 = randarr.reshape((4, 5))
print(randarr_4by5)

replace_maxmium(randarr_4by5, 0, 1)#replacing the max value in each row by zero

[20.55308303  3.46762457 10.56012231  9.68206734 10.331672   15.50237281
  7.54755704 10.34059706 19.46184924  6.22487334 11.04105324 16.56770484
 20.37931367 17.75713468 13.49206914  1.02332147 13.27831891 13.51746566
 12.17329182  4.70013959]
[[20.55308303  3.46762457 10.56012231  9.68206734 10.331672  ]
 [15.50237281  7.54755704 10.34059706 19.46184924  6.22487334]
 [11.04105324 16.56770484 20.37931367 17.75713468 13.49206914]
 [ 1.02332147 13.27831891 13.51746566 12.17329182  4.70013959]]
[[ 0.          3.46762457 10.56012231  9.68206734 10.331672  ]
 [15.50237281  7.54755704 10.34059706  0.          6.22487334]
 [11.04105324 16.56770484  0.         17.75713468 13.49206914]
 [ 1.02332147 13.27831891  0.         12.17329182  4.70013959]]
